/**
 * Id-keyed Console selectors for duration walks (idea#166/#168).
 * Prefer data-testid; never position-based (nth-child / first() as sole identity).
 */
export const sel = {
  consoleOverview: '[data-testid="console-overview"]',
  statusBarIndicator: '[data-testid="status-bar-indicator"]',
  opEntry: '[data-testid="op-entry"]',
  opOverview: '[data-testid="op-overview"]',
  networkTree: '[data-testid="network-tree"]',
  networkAllApps: '[data-testid="network-all-apps"]',
  accountBtn: '[data-testid="account-btn"]',
  settingsBtn: '[data-testid="settings-btn"]',
  settingsPanel: '[data-testid="settings-panel"]',
  loginForm: '[data-testid="login-form"]',
  signIn: '[data-testid="sign-in"]',
  logOut: '[data-testid="log-out"]',
  changePasswordForm: '[data-testid="change-password-form"]',
  changePassword: '[data-testid="change-password"]',
  changePasswordCurrent: '[data-testid="change-password-current"]',
  changePasswordNew: '[data-testid="change-password-new"]',
  changePasswordConfirm: '[data-testid="change-password-confirm"]',
  changePasswordSuccess: '[data-testid="change-password-success"]',
  addOperatorSuccess: '[data-testid="add-operator-success"]',
  manageOperators: '[data-testid="manage-operators"]',
  operatorManagement: '[data-testid="operator-management"]',
  addOperatorForm: '[data-testid="add-operator-form"]',
  addOperator: '[data-testid="add-operator"]',
  firstTimeSetup: '[data-testid="first-time-setup"]',
  firstTimeSetupForm: '[data-testid="first-time-setup-form"]',
  ejectConfirm: '[data-testid="eject-confirm"]',
  ejectConfirmOk: '[data-testid="eject-confirm-ok"]',
  ejectConfirmCancel: '[data-testid="eject-confirm-cancel"]',
  eraseDialog: '[data-testid="erase-dialog"]',
  eraseConfirmName: '[data-testid="erase-confirm-name"]',
  eraseConfirmOk: '[data-testid="erase-confirm-ok"]',
  eraseCancel: '[data-testid="erase-cancel"]',
  eraseComplete: '[data-testid="erase-complete"]',
  eraseDone: '[data-testid="erase-done"]',
  eraseProgress: '[data-testid="erase-progress"]',
  eraseThisDisk: '[data-testid="erase-this-disk"]',
  emptyDiskPanel: '[data-testid="empty-disk-panel"]',
  makeFilesDisk: '[data-testid="make-files-disk"]',
  makeBackupDisk: '[data-testid="make-backup-disk"]',
  configureBackupDisk: '[data-testid="configure-backup-disk"]',
  backupPending: '[data-testid="backup-pending"]',
  backupFormError: '[data-testid="backup-form-error"]',
  backupConfiguredSuccess: '[data-testid="backup-configured-success"]',
  backupMode: (mode: string) => `[data-testid="backup-mode-${mode}"]`,
  backupLinkInstance: (id: string) => `[data-testid="backup-link-instance-${id}"]`,
  installApp: '[data-testid="install-app"]',
  installAppSubmit: '[data-testid="install-app-submit"]',
  installPending: '[data-testid="install-pending"]',
  addFiles: '[data-testid="add-files"]',
  filesShareName: '[data-testid="files-share-name"]',
  filesShareSubmit: '[data-testid="files-share-submit"]',
  diskSectionFiles: '[data-testid="disk-section-files"]',
  restorePanel: '[data-testid="restore-panel"]',
  copyMoveModal: '[data-testid="copy-move-modal"]',
  copyMoveCopy: '[data-testid="copy-move-copy"]',
  copyMoveMove: '[data-testid="copy-move-move"]',
  copyMoveCancel: '[data-testid="copy-move-cancel"]',
  engine: (id: string) => `[data-testid="engine-${id}"]`,
  disk: (id: string) => `[data-testid="disk-${id}"]`,
  instance: (id: string) => `[data-testid="instance-${id}"]`,
  candidate: (id: string) => `[data-testid="candidate-${id}"]`,
  diskView: (id: string) => `[data-testid="disk-view-${id}"]`,
  eject: (diskId: string) => `[data-testid="eject-${diskId}"]`,
  openInstance: (id: string) => `[data-testid="open-instance-${id}"]`,
  startInstance: (id: string) => `[data-testid="start-instance-${id}"]`,
  stopInstance: (id: string) => `[data-testid="stop-instance-${id}"]`,
  backupInstance: (id: string) => `[data-testid="backup-instance-${id}"]`,
  backupToDisk: (diskId: string) => `[data-testid="backup-to-disk-${diskId}"]`,
  installAppItem: (appId: string) => `[data-testid="install-app-item-${appId}"]`,
  restoreInstance: (id: string) => `[data-testid="restore-instance-${id}"]`,
  restoreTarget: (id: string) => `[data-testid="restore-target-${id}"]`,
  restoreBtn: (id: string) => `[data-testid="restore-btn-${id}"]`,
  restoreConfirm: (id: string) => `[data-testid="restore-confirm-${id}"]`,
  restoreCancel: (id: string) => `[data-testid="restore-cancel-${id}"]`,
  removeOperator: (id: string) => `[data-testid="remove-operator-${id}"]`,
  rebootEngine: (id: string) => `[data-testid="reboot-engine-${id}"]`,
  settingsTabEngine: '[data-testid="settings-tab-engine"]',
  settingsTabAccount: '[data-testid="settings-tab-account"]',
  settingsTabAbout: '[data-testid="settings-tab-about"]',
  settingsEngineStatus: '[data-testid="settings-engine-status"]',
  settingsDemoToggle: '[data-testid="settings-demo-toggle"]',
  settingsAboutVersion: '[data-testid="settings-about-version"]',
  settingsChangePasswordForm: '[data-testid="settings-change-password-form"]',
  switchEngineConnect: '[data-testid="switch-engine-connect"]',
  connectionManagement: '[data-testid="connection-management"]',
  connectionMgmtBtn: '[data-testid="connection-mgmt-btn"]',
  connectionScanLabel: '[data-testid="connection-scan-label"]',
  connectionManualLink: '[data-testid="connection-manual-link"]',
  connectionManualHost: '[data-testid="connection-manual-host"]',
  statusBarHostname: '[data-testid="status-bar-hostname"]',
  connectEngineManual: '[data-testid="connect-engine-manual"]',
  connectEngine: (hostname: string) =>
    `[data-testid="connect-engine-${hostname.replace(/\.local$/i, '')}"]`,
} as const;
