/**
 * Id-keyed Console selectors for duration walks (idea#166/#168).
 * Prefer data-testid; never position-based (nth-child / first()).
 */
export const sel = {
  consoleOverview: '[data-testid="console-overview"]',
  opEntry: '[data-testid="op-entry"]',
  opOverview: '[data-testid="op-overview"]',
  networkTree: '[data-testid="network-tree"]',
  accountBtn: '[data-testid="account-btn"]',
  settingsBtn: '[data-testid="settings-btn"]',
  settingsPanel: '[data-testid="settings-panel"]',
  loginForm: '[data-testid="login-form"]',
  signIn: '[data-testid="sign-in"]',
  ejectConfirm: '[data-testid="eject-confirm"]',
  ejectConfirmOk: '[data-testid="eject-confirm-ok"]',
  ejectConfirmCancel: '[data-testid="eject-confirm-cancel"]',
  eraseDialog: '[data-testid="erase-dialog"]',
  eraseConfirmName: '[data-testid="erase-confirm-name"]',
  eraseConfirmOk: '[data-testid="erase-confirm-ok"]',
  eraseCancel: '[data-testid="erase-cancel"]',
  eraseThisDisk: '[data-testid="erase-this-disk"]',
  emptyDiskPanel: '[data-testid="empty-disk-panel"]',
  makeFilesDisk: '[data-testid="make-files-disk"]',
  addFiles: '[data-testid="add-files"]',
  filesShareName: '[data-testid="files-share-name"]',
  filesShareSubmit: '[data-testid="files-share-submit"]',
  diskSectionFiles: '[data-testid="disk-section-files"]',
  engine: (id: string) => `[data-testid="engine-${id}"]`,
  disk: (id: string) => `[data-testid="disk-${id}"]`,
  instance: (id: string) => `[data-testid="instance-${id}"]`,
  candidate: (id: string) => `[data-testid="candidate-${id}"]`,
  diskView: (id: string) => `[data-testid="disk-view-${id}"]`,
  eject: (diskId: string) => `[data-testid="eject-${diskId}"]`,
  openInstance: (id: string) => `[data-testid="open-instance-${id}"]`,
  startInstance: (id: string) => `[data-testid="start-instance-${id}"]`,
  stopInstance: (id: string) => `[data-testid="stop-instance-${id}"]`,
} as const;
